using System.ComponentModel;
using System.Reflection;
using System.Text;
using ModelContextProtocol.Server;

namespace WkMcp;

/// <summary>
/// MCP resources for WolvenKit — readable data exposed by URI, complementing the
/// tools. One reference resource (generated by reflection from the actually
/// registered tools, so never stale) and three resource templates giving access to
/// the game content by path.
/// </summary>
[McpServerResourceType]
public static class WolvenKitResources
{
    [McpServerResource(UriTemplate = "wkmcp://reference",
                       Name = "WolvenKit reference",
                       MimeType = "text/markdown")]
    [Description("Cheat sheet: available MCP tools (list generated from the code), " +
                 "REDengine file formats and the Cyberpunk 2077 modding workflow.")]
    public static string Reference() => _reference ??= BuildReference();

    private static string? _reference;

    [McpServerResource(UriTemplate = "wkmcp://archive/{+path}",
                       Name = "Archive contents",
                       MimeType = "text/plain")]
    [Description("Lists the contents of a Cyberpunk 2077 .archive file, identified " +
                 "by its absolute path after wkmcp://archive/.")]
    public static async Task<string> ArchiveContents(string path)
    {
        if (!File.Exists(path))
            return $"Archive not found: {path}";

        var r = await Cp77ToolsRunner.Shared.RunAsync(
            new[] { "archive", path, "--list" }, CancellationToken.None);
        var output = (r.Stdout + r.Stderr).Trim();
        return output.Length > 0 ? output : "(no output)";
    }

    [McpServerResource(UriTemplate = "wkmcp://cr2w-json/{+path}",
                       Name = "REDengine file as JSON",
                       MimeType = "application/json")]
    [Description("Renders an already-extracted REDengine CR2W file (.mesh, .ent, .app...) as " +
                 "JSON, identified by its absolute path after wkmcp://cr2w-json/.")]
    public static async Task<string> Cr2wJson(string path)
    {
        if (!File.Exists(path))
            return $"File not found: {path}";

        var tmp = Path.Combine(Path.GetTempPath(), "wkmcp-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tmp);
        try
        {
            var r = await Cp77ToolsRunner.Shared.RunAsync(
                new[] { "convert", "serialize", path, "--outpath", tmp }, CancellationToken.None);

            var json = Directory
                .EnumerateFiles(tmp, "*.json", SearchOption.AllDirectories)
                .FirstOrDefault();
            if (json is null)
                return "CR2W → JSON conversion failed:\n" + (r.Stdout + r.Stderr).Trim();

            return await File.ReadAllTextAsync(json);
        }
        finally
        {
            try { Directory.Delete(tmp, recursive: true); } catch { /* best-effort cleanup */ }
        }
    }

    [McpServerResource(UriTemplate = "wkmcp://mods/{+gamePath}",
                       Name = "Installed mods",
                       MimeType = "text/markdown")]
    [Description("Inventory of the installed mods of a Cyberpunk 2077 installation, identified " +
                 "by its root (absolute path) after wkmcp://mods/ : .archive archives, " +
                 "REDmods, .tweak files (TweakXL) and REDscript scripts. Free context " +
                 "before a diagnostic (mod_doctor, analyze_conflicts).")]
    public static string InstalledMods(string gamePath)
    {
        if (!Directory.Exists(gamePath))
            return $"Game folder not found: {gamePath}";

        var sb = new StringBuilder();
        sb.AppendLine($"# Installed mods — {gamePath}");

        var legacy = Path.Combine(gamePath, "archive", "pc", "mod");
        var archives = Directory.Exists(legacy)
            ? Directory.GetFiles(legacy, "*.archive").Select(Path.GetFileName).OrderBy(x => x).ToList()
            : new List<string?>();
        sb.AppendLine();
        sb.AppendLine($"## Archives (archive/pc/mod) — {archives.Count}");
        foreach (var a in archives) sb.AppendLine($"- {a}");

        var modsDir = Path.Combine(gamePath, "mods");
        var redmods = Directory.Exists(modsDir)
            ? Directory.GetDirectories(modsDir).Select(Path.GetFileName).OrderBy(x => x).ToList()
            : new List<string?>();
        sb.AppendLine();
        sb.AppendLine($"## REDmods (mods/) — {redmods.Count}");
        foreach (var m in redmods) sb.AppendLine($"- {m}");

        var tweaksDir = Path.Combine(gamePath, "r6", "tweaks");
        var tweaks = Directory.Exists(tweaksDir)
            ? Directory.EnumerateFiles(tweaksDir, "*", SearchOption.AllDirectories)
                .Where(f => Path.GetExtension(f).ToLowerInvariant() is ".tweak" or ".yaml" or ".yml")
                .Select(f => Path.GetRelativePath(tweaksDir, f)).OrderBy(x => x).ToList()
            : new List<string>();
        sb.AppendLine();
        sb.AppendLine($"## Tweaks (r6/tweaks) — {tweaks.Count}");
        foreach (var t in tweaks) sb.AppendLine($"- {t}");

        var scriptsDir = Path.Combine(gamePath, "r6", "scripts");
        var scriptMods = Directory.Exists(scriptsDir)
            ? Directory.GetDirectories(scriptsDir).Select(Path.GetFileName).OrderBy(x => x).ToList()
            : new List<string?>();
        sb.AppendLine();
        sb.AppendLine($"## REDscript scripts (r6/scripts) — {scriptMods.Count} folder(s)");
        foreach (var s in scriptMods) sb.AppendLine($"- {s}");

        sb.AppendLine();
        sb.AppendLine("To go further: mod_doctor (overall health), analyze_conflicts " +
                      "(overlaps), mod_summary (detail of one archive).");
        return sb.ToString();
    }

    // ──────────────────────────────────────────────────────────────────────
    // Reference generation by reflection over the tool classes: the counts and
    // names come from the real code, not from hand-maintained text.

    internal static IReadOnlyList<string> ToolNames(Type toolType) =>
        toolType.GetMethods(BindingFlags.Public | BindingFlags.Static)
            .Select(m => m.GetCustomAttribute<McpServerToolAttribute>()?.Name)
            .Where(n => !string.IsNullOrEmpty(n))
            .Select(n => n!)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

    internal static IReadOnlyList<(string Name, string Description)> PromptInfos() =>
        typeof(WolvenKitPrompts).GetMethods(BindingFlags.Public | BindingFlags.Static)
            .Select(m => (Attr: m.GetCustomAttribute<McpServerPromptAttribute>(),
                          Desc: m.GetCustomAttribute<DescriptionAttribute>()?.Description ?? ""))
            .Where(t => t.Attr?.Name is not null)
            .Select(t => (t.Attr!.Name!, FirstSentence(t.Desc)))
            .OrderBy(t => t.Item1, StringComparer.Ordinal)
            .ToList();

    internal static IReadOnlyList<(string Name, string UriTemplate)> ResourceInfos() =>
        typeof(WolvenKitResources).GetMethods(BindingFlags.Public | BindingFlags.Static)
            .Select(m => m.GetCustomAttribute<McpServerResourceAttribute>())
            .Where(a => a?.UriTemplate is not null)
            .Select(a => (a!.Name ?? a.UriTemplate!, a.UriTemplate!))
            .OrderBy(t => t.Item2, StringComparer.Ordinal)
            .ToList();

    private static string FirstSentence(string text)
    {
        var idx = text.IndexOf(". ", StringComparison.Ordinal);
        return idx > 0 ? text[..(idx + 1)] : text;
    }

    internal static string BuildReference()
    {
        var offline = ToolNames(typeof(WolvenKitTools));
        var modding = ToolNames(typeof(ModdingTools));
        var scene = ToolNames(typeof(SceneTools));
        var live = ToolNames(typeof(LiveTools));
        var prompts = PromptInfos();
        var total = offline.Count + modding.Count + scene.Count + live.Count;

        var sb = new StringBuilder();
        sb.AppendLine("# WolvenKit / Cyberpunk 2077 — cheat sheet");
        sb.AppendLine();
        sb.AppendLine($"## Available MCP tools ({total} total)");
        sb.AppendLine();
        sb.AppendLine("### Key tools by task");
        sb.AppendLine("- Explore: find_in_archives / archive_info (LRU cache), find_in_cr2w / inspect_cr2w (any CR2W file), inspect_journal / find_journal_entry (.journal)");
        sb.AppendLine("- Read/edit a game file: read_game_file / write_game_file (JSON in one call), cr2w_to_json / json_to_cr2w");
        sb.AppendLine("- Extract: extract_files / uncook (mesh -> glTF, textures -> image; flags meshExportType, meshExporterType, meshExportLodFilter), extract_audio (opus voice-over)");
        sb.AppendLine("- Pack/install: pack_archive, install_mod, build_project, package_mod, scaffold_mod / scaffold_archivexl");
        sb.AppendLine("- TweakDB: tweakdb_query / tweakdb_resolve / describe_tweak_record / dump_records + read_tweak / write_tweak / validate_tweak / install_tweak / lint_tweak");
        sb.AppendLine("- REDscript scripts: read_script / lint_script (line:column syntax validation), generate_redscript_template");
        sb.AppendLine("- Diagnose: mod_doctor, diagnose_logs (6 logs + known-error database), analyze_conflicts, analyze_dependencies / check_requirements, migration_check");
        sb.AppendLine("- Validate: validate_xl, validate_item_mod (full ArchiveXL chain), validate_appearance (.app -> .mesh), lint_mod");
        sb.AppendLine("- Appearances: list_entity_appearances, resolve_dynamic_appearance; export_entity stays experimental (headless refusal on NPCs)");
        sb.AppendLine("- Safety: backup_mods / restore_mods, toggle_mods (bisection), uninstall_mod / uninstall_redmod / uninstall_tweak");
        sb.AppendLine("- In-game (offline): launch_game, tail_game_logs");
        sb.AppendLine("- Scenes (.scene): inspect_scene (structure), scene_graph (flow), find_in_scene (locate node/dialogue), validate_scene (graph + dialogue integrity), scene_dependencies / scene_events, scene_set_actor / scene_replace_resource (editing), extract_scene_localization / apply_scene_localization (dialogue translation), scaffold_scene");
        sb.AppendLine("- Live (game running + CETBridge mod): live_status first, then the live_* tools (player state, inventory, teleport, live TweakDB, quest facts, event observation)");
        sb.AppendLine();
        sb.AppendLine($"### Full list — archives/CR2W/TweakDB/projects tools ({offline.Count})");
        sb.AppendLine(string.Join(", ", offline));
        sb.AppendLine();
        sb.AppendLine($"### Full list — modding workflow tools ({modding.Count})");
        sb.AppendLine(string.Join(", ", modding));
        sb.AppendLine();
        sb.AppendLine($"### Full list — scene tools ({scene.Count})");
        sb.AppendLine(string.Join(", ", scene));
        sb.AppendLine();
        sb.AppendLine($"### Full list — live in-game tools ({live.Count})");
        sb.AppendLine(string.Join(", ", live));
        sb.AppendLine();
        sb.AppendLine("Each tool returns a structured JSON result: { ok, status, summary,");
        sb.AppendLine("produced, warnings, errors, log }. The bulky log is truncated while");
        sb.AppendLine("preserving head + errors + tail. Most tools accept a `verbose=true`");
        sb.AppendLine("parameter to retrieve the full log (debug).");
        sb.AppendLine();
        sb.AppendLine($"## MCP prompts ({prompts.Count} recipes)");
        foreach (var (name, desc) in prompts)
            sb.AppendLine($"- {name} : {desc}");
        sb.AppendLine();
        sb.AppendLine("## Common REDengine formats");
        sb.AppendLine("- .archive: asset container (Kraken compression)");
        sb.AppendLine("- .mesh: 3D model            - .xbm: texture");
        sb.AppendLine("- .ent / .app: entities and appearances");
        sb.AppendLine("- .tweak: TweakDB override (TweakXL, YAML)   - .reds: REDscript script");
        sb.AppendLine("- .json: editable representation of a CR2W file");
        sb.AppendLine();
        sb.AppendLine("## Modding workflow (asset replacement)");
        sb.AppendLine("1. find_in_archives to locate the wanted file");
        sb.AppendLine("2. read_game_file to read it as JSON (or extract_files / uncook)");
        sb.AppendLine("3. edit the JSON, then write_game_file (or import_raw)");
        sb.AppendLine("4. pack_archive on the source folder");
        sb.AppendLine("5. install_mod to drop the archive into <game>/archive/pc/mod/");
        sb.AppendLine();
        sb.AppendLine("## Folders of a Cyberpunk 2077 installation");
        sb.AppendLine("- archive/pc/content/ : base game assets");
        sb.AppendLine("- archive/pc/mod/     : installed .archive mods");
        sb.AppendLine("- mods/               : REDmod mods");
        sb.AppendLine("- r6/tweaks/          : .tweak files (TweakXL)");
        sb.AppendLine("- r6/scripts/         : .reds scripts (redscript)");
        sb.AppendLine("- r6/logs/            : logs (diagnose_logs / tail_game_logs)");
        return sb.ToString();
    }
}
